name: SONOMA SOUND
favicon: null
layout_spectrum: 0.50482
typography_spectrum: 0.50477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#974807'
    - '#b7b7b7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
