name: SONOMA SOUND
favicon: null
layout_spectrum: 0.50482
typography_spectrum: 0.50477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c090c'
    - '#ffffff'
    - '#756f6f'
    - '#454545'
    - '#9eadc9'
  brandStrength: 0.8544663321226835
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
