name: SONOMA SOUND
favicon: null
layout_spectrum: 0.76374
typography_spectrum: 0.49662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#808080'
    - '#000000'
    - '#814104'
    - '#fd8105'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
